[tool.bumpversion]
current_version = "0.2.1"
## Commit & tag handled by pipeline
commit = false
tag = false
tag_name = "v{new_version}"
allow_dirty = false

[[tool.bumpversion.files]]
filename = "VERSION"
search = "{current_version}"
replace = "{new_version}"
