---
name: Test Astro version bump

on:
  push:
    branches:
      - feat/astro-pipelines
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    uses: redjax/PipelineTemplates/.github/workflows/astro-version-bump.yml@feat/astro-workflows
    with:
      base-branch: main

      templates-ref: feat/astro-workflows

      version-file: VERSION
      bump-config: .bumpversion.toml

      pr-branch: bump/astro-site-version
      pr-title: "chore(release): bump Astro site version [skip ci]"
      pr-labels: automated,release

      dry-run: false
      auto-merge: false
      auto-merge-method: merge

    secrets:
      release-bot-pat: ${{ secrets.RELEASE_BOT_PAT }}
